#!/usr/bin/env bash

set -e

application_name=solvcon
application_branch=${VERSION:-master}
application_full=$application_name-$application_branch
application_src=${DEVENVROOT}/flavors/${DEVENVFLAVOR}/src/${application_full}
application_upstream_project_root=${APP_UPSTREAM_PROJECT_ROOT:-https://github.com/solvcon}

syncgit ${application_upstream_project_root} ${application_name} ${application_branch}

export DEVENVAPP=${DEVENVROOT}/flavors/${DEVENVFLAVOR}/application-${application_name}
mkdir -p ${DEVENVAPP}

ln -s ${application_src} ${DEVENVAPP}/${application_name}

# devenv scripts to build SOLVCON application
DEVENVAPPBUILDSRC=${DEVENVROOT}/applications/solvcon
source ${DEVENVAPPBUILDSRC}/entry.sh

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
