name: Application Build - SOLVCON
on:
  schedule:
    - cron: '21 18 * * 5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-24.04, macos-latest]
        fail-fast: false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set DEVENV_WORKSPACE
      run: echo "DEVENV_WORKSPACE=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
    - name: Configure SSH
      if: matrix.os == 'disable'
      run: |
        source contrib/ci-setup-ssh.sh
    - name: Dependency (Ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-setup-apt.sh
    - name: Cache Homebrew downloads (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Homebrew
        key: brew-${{ runner.os }}
        restore-keys: |
          brew-${{ runner.os }}-
    - name: Dependency (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update --quiet
        brew install --cask mactex-no-gui
        TEXBIN="/Library/TeX/texbin"
        echo "PATH=${TEXBIN}:$PATH" >> $GITHUB_ENV
        if [[ "$(uname -m)" == "arm64" ]]; then
          echo "PYTHON_DECIMAL_WITH_MACHINE=uint128" >> $GITHUB_ENV
        else
          echo "PYTHON_DECIMAL_WITH_MACHINE=x64" >> $GITHUB_ENV
        fi
    - name: Launch SOLVCON
      run: |
        source ${DEVENV_WORKSPACE}/scripts/init
        devenv add prime
        devenv use prime
        devenv show
        devenv launch solvcon
    - name: Show Dependency
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-show-dep.sh
    - name: Show Python Env
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-show-python-env.sh
    - name: SOLVCON Function Test From Package
      run: |
        source ${DEVENV_WORKSPACE}/contrib/ci-solvcon-function-test.sh
