#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

pkgname=the_silver_searcher

if [ "${SRCSYNC}" == "tarball" ] ; then

  pkgver=${VERSION:-2.2.0}
  pkgfull=${pkgname}-${pkgver}
  pkgfn=${pkgfull}.tar.gz
  pkgurl=https://geoff.greer.fm/ag/releases/${pkgname}-${pkgver}.tar.gz

  download_md5 $pkgfn $pkgurl 958a614cbebf47b2f27a7d00a5bb1bcb

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd > /dev/null

elif [ "${SRCSYNC}" == "git" ] ; then

  pkgbranch=${VERSION:-master}
  pkgfull=$pkgname

  # unpack (clone)
  syncgit https://github.com/${pkgname} ${pkgname} ${pkgbranch} ${pkgfull}

else

  display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

# build.

cfgcmd=("env")
cfgcmd+=("CFLAGS=-I${DEVENVPREFIX}/include")
cfgcmd+=("LDFLAGS=-L${DEVENVPREFIX}/lib")
cfgcmd+=("./configure")
cfgcmd+=("--prefix=${DEVENVPREFIX}")

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j $NP
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
