#!/usr/bin/env bash

set -e

pkgname=bzip2
pkgbranch=${VERSION:-master}
pkgfull=$pkgname-$pkgbranch

syncgit https://gitlab.com/bzip2 ${pkgname} ${pkgbranch} ${pkgfull}

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null
  mkdir -p build
  pushd build > /dev/null
    cmakecmd=("cmake")
    cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")
    cmakecmd+=("-DENABLE_SHARED_LIB=ON")
    cmakecmd+=("../")

    buildcmd cmake.log "${cmakecmd[@]}"
    buildcmd make.log make -j ${NP}
    buildcmd install.log make install
  popd > /dev/null
popd > /dev/null
# vim: set et nobomb ft=bash ff=unix fenc=utf8:
