#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

pkgname=cmake

if [ "${SRCSYNC}" == "tarball" ] ; then

  pkgver=${VERSION:-4.0.1}
  pkgfull=${pkgname}-${pkgver}
  pkgfn=${pkgfull}.tar.gz
  pkgurl=https://github.com/Kitware/CMake/releases/download/v${pkgver}/${pkgfn}

  download_md5 $pkgfn $pkgurl 534b4af60e0b4b3fa43199d75d2debef

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd > /dev/null

elif [ "${SRCSYNC}" == "git" ] ; then

  pkgbranch=${VERSION:-master}
  pkgfull=$pkgname

  # unpack (clone)
  syncgit https://github.com/Kitware ${pkgname} ${pkgbranch}

else

  devenv_display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

# build.

cfgcmd=("env")
cfgcmd+=("CFLAGS=-I${DEVENVPREFIX}/include")
cfgcmd+=("LDFLAGS=-L${DEVENVPREFIX}/lib")
cfgcmd=("./configure")
cfgcmd+=("--prefix=${DEVENVPREFIX}")

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
