#!/usr/bin/env bash

set -e

if [ -z "${SYNCGIT}" ]; then

  pkgname=Cython
  pkgver=${VERSION:-0.29.30}
  pkgfull=$pkgname-$pkgver
  pkgfn=$pkgfull.tar.gz
  pkgurl=https://files.pythonhosted.org/packages/d4/ad/7ce0cccd68824ac9623daf4e973c587aa7e2d23418cd028f8860c80651f5/$pkgfn

  download_md5 $pkgfn $pkgurl 3cf4001b4be42a263f163865235c39d8

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd

else

  pkgname=cython
  pkgbranch=${VERSION:-master}
  pkgfull=${pkgname}

  syncgit https://github.com/cython ${pkgname} ${pkgbranch} ${pkgfull}

fi

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  PYTHON=${PYTHON_EXE:-${DEVENVPREFIX}/bin/python3}

  buildcmd build.log ${PYTHON} setup.py build -j ${NP}
  buildcmd install.log ${PYTHON} setup.py install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
