#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

if [ "${SRCSYNC}" == "tarball" ] ; then

  pkgname=Cython
  pkgver=${VERSION:-0.29.32}
  pkgfull=${pkgname}-${pkgver}
  pkgfn=${pkgfull}.tar.gz
  pkgurl=https://files.pythonhosted.org/packages/4c/76/1e41fbb365ad20b6efab2e61b0f4751518444c953b390f9b2d36cf97eea0/${pkgfn}

  download_md5 $pkgfn $pkgurl 91c36ea86c00adcc5c1c11cf48b733c0

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd

elif [ "${SRCSYNC}" == "git" ] ; then

  pkgname=cython
  pkgbranch=${VERSION:-master}
  pkgfull=${pkgname}

  # unpack (clone)
  syncgit https://github.com/cython ${pkgname} ${pkgbranch} ${pkgfull}

else

  display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

# build.

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  PYTHON=${PYTHON_EXE:-${DEVENVPREFIX}/bin/python3}

  buildcmd build.log ${PYTHON} setup.py build -j ${NP}
  buildcmd install.log ${PYTHON} setup.py install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
