#!/usr/bin/env bash

set -e

if [ -z "${SYNCGIT}" ]; then

  pkgname=gmsh
  pkgver=${VERSION:-4.8.4}
  pkgfull=${pkgname}-${pkgver}-source
  pkgfn=$pkgfull.tar.gz
  pkgurl=http://gmsh.info/src/$pkgfull.tgz
  download_md5 $pkgfn $pkgurl 1e7212dfb1319d745ffb477a7a3ff124

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd

else

  pkgname=gmsh
  pkgbranch=${VERSION:-master}
  pkgfull=$pkgname-$pkgbranch

  syncgit https://gitlab.onelab.info/gmsh/ ${pkgname} ${pkgbranch} ${pkgfull}

fi

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  mkdir -p build

  cd build

  cmakecmd=("cmake")
  cmakdcmd+=("-DCMAKE_PREFIX_PATH=${DEVENVPREFIX}")
  cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")
  cmakecmd+=("-DBUILD_SHARED_LIBS=ON")
  cmakecmd+=("-DENABLE_NUMPY=ON")
  cmakecmd+=("-DENABLE_OS_SPECIFIC_INSTALL=OFF")
  cmakecmd+=("-DENABLE_MATCH=OFF")
  cmakecmd+=("-DENABLE_PETSC=OFF")
  cmakecmd+=("-DENABLE_SLEPC=OFF")
  cmakecmd+=("../")

  buildcmd cmake.log "${cmakecmd[@]}"
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
