#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

pkgname=libevent

if [ "${SRCSYNC}" == "tarball" ] ; then

  pkgver=${VERSION:-2.1.12-stable}
  pkgfull=${pkgname}-${pkgver}
  pkgfn=${pkgfull}.tar.gz
  pkgurl=https://github.com/${pkgname}/${pkgname}/releases/download/release-${pkgver}/${pkgfn}

  download_md5 $pkgfn $pkgurl b5333f021f880fe76490d8a799cd79f4

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd > /dev/null

elif [ "${SRCSYNC}" == "git" ] ; then

  pkgbranch=${VERSION:-master}
  pkgfull=$pkgname

  # unpack (clone)
  syncgit https://github.com/${pkgname} ${pkgname} ${pkgbranch} ${pkgfull}

else

  display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

# build.

cfgcmd=("./configure")
cfgcmd+=("--prefix=${DEVENVPREFIX}")

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j $NP
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
