#!/usr/bin/env bash

set -e

pkgname=libffi
pkgver=${VERSION:-3.0.13}
pkgfull=$pkgname-$pkgver
pkgfn=$pkgfull.tar.gz
pkgmd5=45f3b6dbc9ee7c7dfbbbc5feba571529
pkgurl=https://src.fedoraproject.org/repo/pkgs/libffi/${pkgfn}/${pkgmd5}/${pkgfn}

download_md5 $pkgfn $pkgurl $pkgmd5

mkdir -p ${DEVENVCURRENTROOT}/src
pushd ${DEVENVCURRENTROOT}/src > /dev/null
  tar xf ${DEVENVDLROOT}/$pkgfn
popd > /dev/null

cfgcmd=("./configure")
cfgcmd+=("--prefix=${DEVENVPREFIX}")

pushd ${DEVENVCURRENTROOT}/src/${pkgfull} > /dev/null

  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
