#!/usr/bin/env bash

set -e

if [ -z "${SYNCGIT}" ]; then
  pkgname=netcdf
  pkgver=${VERSION:-4.4.1.1}
  pkgfull=$pkgname-$pkgver
  pkgmd5=${PKGMD5:-5b851c3dc0a54185aecb44980ed3a334}

  pkgfn=$pkgfull.tar.gz
  pkgurl=ftp://ftp.unidata.ucar.edu/pub/$pkgname/$pkgfn

  # download tarball
  download_md5 $pkgfn $pkgurl $pkgmd5

  # unpack.
  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null

    tar xf ${DEVENVDLROOT}/$pkgfn

  popd
else
  pkgname=netcdf-c
  pkgbranch=${VERSION:-v4.4.1.1}
  pkgfull=${pkgname}-${pkgbranch}

  # unpack (clone / pull)
  syncgit https://github.com/Unidata ${pkgname} ${pkgbranch}
fi

mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull}/build
pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull}/build > /dev/null
  cmakecmd=("cmake")
  cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")
  cmakecmd+=("-DBUILD_SHARED_LIBS=ON")
  cmakecmd+=("-DENABLE_NETCDF_4=ON")
  cmakecmd+=("-DENABLE_DAP=OFF")
  cmakecmd+=("-DENABLE_TESTS=OFF")
  cmakecmd+=("../")

  buildcmd cmake.log "${cmakecmd[@]}"
  buildcmd make.log make install -j $NP
popd

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
