#!/usr/bin/env bash

set -e

if [ -z "${SYNCGIT}" ]; then

  pkgname=OpenBLAS
  pkgver=${VERSION:-0.3.17}
  pkgfull=$pkgname-$pkgver
  pkgfn=$pkgfull.tar.gz
  pkgurl=https://github.com/xianyi/OpenBLAS/releases/download/v${pkgver}/${pkgfn}

  download_md5 $pkgfn $pkgurl 5429954163bcbaccaa13e11fe30ca5b6

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd

else

  pkgname=OpenBLAS
  pkgbranch=${VERSION:-develop}
  pkgfull=${pkgname}

  # unpack (clone / pull)
  syncgit https://github.com/xianyi ${pkgname} ${pkgbranch} ${pkgfull}

fi

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  mkdir -p build
  cd build

  cmakecmd=("cmake")
  cmakecmd+=("-DCMAKE_Fortran_COMPILER=gfortran")
  cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")
  cmakecmd+=("-DBUILD_SHARED_LIBS=ON")
  cmakecmd+=("-DCMAKE_Fortran_FLAGS=-fPIC -O3")

  if [[ ${DEVENVFLAVOR} == dbg* ]] ; then
    cmakecmd+=("-DCMAKE_BUILD_TYPE=Debug")
  fi

  cmakecmd+=("../")
  buildcmd cmake.log "${cmakecmd[@]}"
  buildcmd make.log make install -j $NP

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
