#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

if [ "${SRCSYNC}" == "tarball" ] ; then

  pkgname=openssl
  pkgver=${VERSION:-1.1.1m}
  pkgfull=$pkgname-$pkgver
  pkgfn=$pkgfull.tar.gz
  pkgurl=https://www.openssl.org/source/$pkgfn

  download_md5 $pkgfn $pkgurl 8ec70f665c145c3103f6e330f538a9db

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd

elif [ "${SRCSYNC}" == "git" ] ; then

  pkgname=openssl
  pkgbranch=${VERSION:-master}
  pkgfull=${pkgname}

  syncgit https://github.com/openssl ${pkgname} ${pkgbranch} ${pkgfull}

else

  devenv_display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  cfgcmd=("./config")
  cfgcmd+=("--prefix=${DEVENVPREFIX}")
  cfgcmd+=("--openssldir=${DEVENVPREFIX}/share/ssl")

  # build.
  buildcmd configure.log "${cfgcmd[@]}"
  buildcmd make.log make -j ${NP}
  buildcmd install.log make -j ${NP} install

popd > /dev/null
# vim: set et nobomb ft=bash ff=unix fenc=utf8:
