#!/usr/bin/env bash

set -e

# NOTE: Default is to use git!
if [ -n "${SYNCGIT}" ]; then

  pkgname=pybind11
  pkgver=${VERSION:-2.7.0}
  pkgfull=$pkgname-$pkgver
  pkgfn=$pkgfull.tar.gz
  pkgurl=https://github.com/pybind/pybind11/archive/refs/tags/v${pkgver}.tar.gz

  download_md5 $pkgfn $pkgurl bd742c80621babef4814cc2df041490d

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null
    tar xf ${DEVENVDLROOT}/$pkgfn
  popd > /dev/null

else

  pkgname=pybind11
  pkgbranch=${VERSION:-master}
  pkgfull=$pkgname

  # unpack (clone)
  syncgit https://github.com/pybind ${pkgname} ${pkgbranch} ${pkgfull}

fi

# build.

# prepare files for building.
if [ ! -e ${DEVENVPREFIX}/bin/python3 ]; then
    display -e "Python3 not exist!!"
    exit
fi

PYTHON=${DEVENVPREFIX}/bin/python3

cmakecmd=("cmake")
cmakecmd+=("-DPYTHON_EXECUTABLE:FILEPATH=${PYTHON}")
cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")
cmakecmd+=("-DPYBIND11_TEST=OFF")

if [[ $DEVENVFLAVOR == opt* ]] ; then
  cmakecmd+=("-DCMAKE_BUILD_TYPE=Release")
elif [[ $DEVENVFLAVOR == dbg* ]] ; then
  cmakecmd+=("-DCMAKE_BUILD_TYPE=Debug")
fi

mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull}/build

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull}/build > /dev/null

  buildcmd cmake.log "${cmakecmd[@]}" ..
  buildcmd make.log make -j $NP
  buildcmd install.log make install

  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null
    buildcmd build/setup.log $PYTHON setup.py install
  popd > /dev/null

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
