#!/usr/bin/env bash

set -e

pkgname=xz
pkgbranch=${VERSION:-master}
pkgfull=$pkgname-$pkgbranch

syncgit https://github.com/xz-mirror/ ${pkgname} ${pkgbranch}

pushd ${DEVENVROOT}/flavors/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  mkdir -p build

  cd build

  cmakecmd=("cmake")
  cmakecmd+=("-DCMAKE_INSTALL_PREFIX=${DEVENVPREFIX}")
  cmakecmd+=("-DBUILD_SHARED_LIBS=ON")
  cmakecmd+=("../")

  buildcmd cmake.log "${cmakecmd[@]}"
  buildcmd make.log make install -j $NP

popd > /dev/null
# vim: set et nobomb ft=bash ff=unix fenc=utf8:
