#!/usr/bin/env bash

set -e

pkgname=zlib
pkgbranch=${VERSION:-master}
pkgfull=${pkgname}-${pkgbranch}

syncgit https://github.com/madler ${pkgname} ${pkgbranch}

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  # build.
  buildcmd configure.log ./configure --prefix=${DEVENVPREFIX}
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
