#!/usr/bin/env bash

set -e

SRCSYNC=${SRCSYNC:-tarball}

if [ "${SRCSYNC}" == "tarball" ]; then

  pkgname=zlib
  pkgver=${VERSION:-v1.3.1}
  pkgfull=${pkgname}-${pkgver:1}
  pkgfn=${pkgfull}.tar.gz
  pkgurl=https://github.com/madler/zlib/archive/refs/tags/${pkgver}.tar.gz
  download_md5 ${pkgfn} ${pkgurl} ddb17dbbf2178807384e57ba0d81e6a1

  mkdir -p ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src
  pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src > /dev/null
    tar zxf ${DEVENVDLROOT}/$pkgfn
  popd > /dev/null

elif [ "${SRCSYNC}" == "git" ]; then

  pkgname=zlib
  pkgbranch=${VERSION:-master}
  pkgfull=${pkgname}-${pkgbranch}

  syncgit https://github.com/madler ${pkgname} ${pkgbranch}

else

  devenv_display -e "Invalid \${SRCSYNC} ${SRCSYNC}"
  exit

fi

if [ "${DEVENV_DLONLY}" == "1" ] ; then
  echo "\${DEVENV_DLONLY}=1 ; existing"
  exit 1
else
  echo "if you want to exit after downloading: export \${DEVENV_DLONLY}=1"
fi

pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null

  # build.
  buildcmd configure.log ./configure --prefix=${DEVENVPREFIX}
  buildcmd make.log make -j ${NP}
  buildcmd install.log make install

popd > /dev/null
# vim: set et nobomb ft=bash ff=unix fenc=utf8:
